### ISSUE TITLE
请问大佬插件要装在zhenxun上要修改什么部分呢

### ISSUE THREAD

**Issue by wangjiahui1126** [noneplugin/nonebot-plugin-shindan#11]
自己实在研究不明白

**Comment by MeetWq** [comment]
不用修改

**Comment by Nenot233** [comment]
自己写个真寻的适配就能用了，无需修改任何东西

**Comment by Nenot233** [comment]
_zx_plugin_name__ = '趣味占卜'
__plugin_usage__ = """
usage：
    shindanmaker趣味占卜
    指令：
        发送“占卜列表”查看可用占卜
        发送“{占卜名} {名字}”使用占卜
        人设生成 ATRI(随意修改玩家名字)
        
        添加占卜 {id} {指令}
        如：添加占卜 917962 人设生成

        删除占卜 {id}
        如：删除占卜 917962

        设置占卜 {id} {mode}
        设置占卜输出模式：'text' 或 'image'(默认)
        如：设置占卜 360578 text
""".strip()
__plugin_des__ = "shindanmaker趣味占卜"
__plugin_cmd__ = ["趣味占卜"]
__plugin_type__ = ("群内小游戏",)
__plugin_settings__ = {
    "level": 5,
    "default_status": True,
    "limit_superuser": False,
    "cmd": ["趣味占卜"],
}

**Comment by MeetWq** [comment]
真寻已经可以读取 PluginMetadata 格式的元数据了，如果没有特殊需求的话可以不做任何修改；
如果想定义分类、权限之类的东西，可以按楼上那样的格式写在 `__init__.py` 里；具体看真寻文档
