### ISSUE TITLE
缺失图片

### ISSUE THREAD

**Issue by Danwk2333** [noneplugin/nonebot-plugin-shindan#13]
后台无报错，但是不显示表格图片
![image](https://user-images.githubusercontent.com/106854600/203594736-92792070-fc46-4f6d-bda2-cc634352b994.png)
这个是原链接，以下是bot生成的
![image](https://user-images.githubusercontent.com/106854600/203594867-bd181e31-6700-40e2-a59b-d0a1688b00a3.png)
另一个同样不显示的生成器网址编号是919572，和魔法人生940824等，但是结果为二次元图片的正常显示比如抽高达361845和抽老婆1075116，插件均已更新

**Comment by MeetWq** [comment]
因为这种表是网页渲染的，可能会比较慢
https://github.com/noneplugin/nonebot-plugin-shindan/blob/ca754cef242b037c99ac577dbf0809b979896352/nonebot_plugin_shindan/shindanmaker.py#L81
可以试着把这里的`wait=2000`改大点

**Comment by Danwk2333** [comment]
> 因为这种表是网页渲染的，可能会比较慢
> 
> https://github.com/noneplugin/nonebot-plugin-shindan/blob/ca754cef242b037c99ac577dbf0809b979896352/nonebot_plugin_shindan/shindanmaker.py#L81
> 
> 
> 可以试着把这里的`wait=2000`改大点

从2000到5000，10000改成wait=20000 还是空白的，有可能是网络问题吗

**Comment by a930389426** [comment]
我也出现这种问题了，也是昨天晚上突然就开始的

**Comment by a930389426** [comment]
涉及到图表的全部无法显示

**Comment by MeetWq** [comment]
最新版修了
