### ISSUE TITLE
数据库初始化后未建表

### ISSUE THREAD

**Issue by cute-cirno** [noneplugin/nonebot-plugin-shindan#16]
使用nb-cli安装shindan后初次启动，触发错误：初始化后执行的函数出错，内容是 no such table。应该是__init__文件37行执行select语句抛出的报错。
![image](https://user-images.githubusercontent.com/69642894/227696349-303bcfc0-b4b7-463d-a73f-8717990e6628.png)

**Comment by he0119** [comment]
试试将 nonebot-plugin-datastore 升级至 0.6.1，应该可以解决这个问题。
