### ISSUE TITLE
更新之后出现cannot load plugin nonebot_plugin_datastore

### ISSUE THREAD

**Issue by xi-yue-233** [noneplugin/nonebot-plugin-shindan#20]
![image](https://user-images.githubusercontent.com/58218656/231649137-28c0c3ee-97e0-40f9-b320-a0d2ff4e056a.png)

**Comment by xi-yue-233** [comment]
![image](https://user-images.githubusercontent.com/58218656/231649659-56ad1a30-28d4-4858-bf30-c86bcf1e784c.png)

**Comment by MeetWq** [comment]
你需要更新 `nonebot-plugin-datastore`
插件要求 `0.6.0a1` 以上版本
![Snipaste_2023-04-13_12-10-33](https://user-images.githubusercontent.com/33149974/231650809-329e03a8-608b-4d89-9c78-8b883a85baf0.png)

**Comment by xi-yue-233** [comment]
> 你需要更新 `nonebot-plugin-datastore` 插件要求 `0.6.0a1` 以上版本 ![Snipaste_2023-04-13_12-10-33](https://user-images.githubusercontent.com/33149974/231650809-329e03a8-608b-4d89-9c78-8b883a85baf0.png)

完了，我好像有别的插件跟shindan撞依赖了，那个插件依赖的是sqla1.4

**Comment by xi-yue-233** [comment]
> 你需要更新 `nonebot-plugin-datastore` 插件要求 `0.6.0a1` 以上版本 ![Snipaste_2023-04-13_12-10-33](https://user-images.githubusercontent.com/33149974/231650809-329e03a8-608b-4d89-9c78-8b883a85baf0.png)

貌似这个插件更新之后就装不了nonebot_plugin_wordcloud了，因为nonebot_plugin_wordcloud依赖nonebot-plugin-chatrecorder，那个插件的nonebot-plugin-datastore还是比较老的版本

**Comment by MeetWq** [comment]
`nonebot-plugin-chatrecorder` 早就更新了啊

**Comment by MeetWq** [comment]
建议使用依赖管理工具，如 `poetry` 或 `pdm`
