### ISSUE TITLE
RuntimeError: No active exception to reraise

### ISSUE THREAD

**Issue by a930389426** [noneplugin/nonebot-plugin-shindan#21]
![image](https://user-images.githubusercontent.com/59648220/232707335-1b72f8eb-7eac-45ad-bb0b-5e76dfbbcddc.png)

**Comment by MeetWq** [comment]
应该是网络问题，你有多次试过吗

**Comment by MeetWq** [comment]
所有id都有问题？不是的话看看出错的id
