### ISSUE TITLE
遇到无法添加&删除占卜的解决方法

### ISSUE THREAD

**Issue by ElaineOwO** [noneplugin/nonebot-plugin-shindan#24]
自己是机器人主人  机器人只能响应“占卜列表”  没有添加起始符  “添加占卜“和”删除占卜“都没响应应。。前面加艾特也不行 
![image](https://user-images.githubusercontent.com/126962415/235937344-885a51f7-27eb-4004-9339-fc4ce6cc38b9.png)

**Comment by ElaineOwO** [comment]
我day到rua   原来是需要手动设置superuser 不然没有权限修改占卜列表

**Comment by MeetWq** [comment]
已在readme中补充说明
