### ISSUE TITLE
【报错】启动nb时数据库错误

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-shindan#28]
现在希望找的数据库路径修改
![image](https://github.com/noneplugin/nonebot-plugin-shindan/assets/70925546/3203b0fa-d899-47f7-a84e-0c912f158ceb)

**Comment by MeetWq** [comment]
用 `nb datastore dir` 可以显示数据库路径，可以手动把表删掉

**Comment by Agnes4m** [comment]
这个问题解决了，但是生成占卜图片的时候，似乎没有渲染，但是占卜列表图是渲染过的
![image](https://github.com/noneplugin/nonebot-plugin-shindan/assets/70925546/2259ece7-b758-4876-8b2c-ef8351890ded)
![image](https://github.com/noneplugin/nonebot-plugin-shindan/assets/70925546/7b635d3e-cfbc-4c40-9046-1124f9c3c1e5)

**Comment by MeetWq** [comment]
我这边没问题，你检查一下插件版本，以及 templates 下的文件是否一致

**Comment by Agnes4m** [comment]
我是用git clone的方式下载的，服务器为winserver2012,python版本为3.11.3.

刚刚重新git clone并移动其中文件夹，任然出现占卜图片无法渲染的情况
