### ISSUE TITLE
希望能够调整一下占卜列表的图

### ISSUE THREAD

**Issue by Sihnbaobao** [noneplugin/nonebot-plugin-shindan#29]
如果只有比较少的内容还好，但如果添加的比较多的占卜内容，他就会一直往下长？这样一发占卜列表，预览那个长图就没那么方便，或许能够出个配置可以选择是默认竖图，或者能更改为类似memes那样的图的形式。

**Comment by MeetWq** [comment]
调整了占卜列表图的格式，应该会好一点
