### ISSUE TITLE
[BUG] onebot v11 下发不出图片

### ISSUE THREAD

**Issue by Cvandia** [noneplugin/nonebot-plugin-shindan#36]
### 截图
![image](https://github.com/noneplugin/nonebot-plugin-shindan/assets/106718176/c972d7ed-08fb-48e5-9191-ec18b58b0a7c)
![image](https://github.com/noneplugin/nonebot-plugin-shindan/assets/106718176/c3b8f0bf-b54e-4ff0-b2c9-aa571b4f2c7c)
### 怎么产生的
发送对应的占卜指令以及“占卜列表”后无反应，但发送删除添加占卜指令时，有对应文字说明
### 版本
nonebot-plugin-shindan = 0.6.0

**Comment by MeetWq** [comment]
麻烦吧 DEBUG 打开，看发送对应指令时有没有处理

**Comment by Cvandia** [comment]
已解决，账号风控导致
