### ISSUE TITLE
Help：无法正常响应人名参数

### ISSUE THREAD

**Issue by Cvandia** [noneplugin/nonebot-plugin-shindan#42]
![Image_1728729256993.png](https://github.com/user-attachments/assets/045b0c01-a282-46f0-8b19-4bcf1bdb5a68)

正确获取到人名
![Image_1728729611983.png](https://github.com/user-attachments/assets/df1fca80-1c4f-4356-a940-cad72d76ab41)

**Comment by MeetWq** [comment]
#40
