### ISSUE TITLE
关于ShindanMaker这个插件报错问题

### ISSUE THREAD

**Issue by Winj1e** [noneplugin/nonebot-plugin-shindan#5]
![image](https://user-images.githubusercontent.com/105339518/168427049-3ab0aa50-8c17-4fcf-ab50-1f0739cee5de.png)
如图我装插件出现了这个问题，结果问问题问错地方了，首先我先在这里道个歉，我不知道不能在那里评论，事后我想把这个问题隐藏结果隐藏不了，如果对您造成了什么影响我先在这里说声抱歉，确实是我的问题，您说我插件没装上，我又重新装了一下插件，也没显示报错，如下图
![image](https://user-images.githubusercontent.com/105339518/168427145-8850a709-ddeb-4b26-aa92-3ae3d7f1cb3b.png)
结果运行的结果还是和原来一样，所以说这是出现了什么问题？

**Comment by MeetWq** [comment]
你加载插件的时候是不是用的 `nonebot-plugin-shindan` ? 用 `nonebot_plugin_shindan` 试试

**Comment by Winj1e** [comment]
啊这，确实这样，打扰了
