### ISSUE TITLE
需要登录推特的怎么处理啊

### ISSUE THREAD

**Issue by huihuiismywife** [noneplugin/nonebot-plugin-shindan#6]
![QQ图片20220615150556](https://user-images.githubusercontent.com/107234845/173764251-7ffb0f9f-3242-43e1-b81e-815aa5899d84.png)
如图，他需要绑定账户才能使用，我这边在电脑上绑定后就可以正常使用了，但是在云服务器上搞不了，求解啊 _(:з」∠)_

**Comment by MeetWq** [comment]
加了 cookie 设置，可以逝世

**Comment by huihuiismywife** [comment]
这就逝世去 （づ￣3￣）づ╭❤～

**Comment by huihuiismywife** [comment]
逝完回来了，确实逝世了（流泪猫猫头.jpg）
![QQ截图20220618134511](https://user-images.githubusercontent.com/107234845/174424705-13fc03d7-ea40-4315-bd1b-053f45de3243.png)
![QQ图片20220618134615](https://user-images.githubusercontent.com/107234845/174424709-6855398f-c09d-47ea-8bcb-d129cc73d561.png)

放上session后边的字符串后用卖萌这种发文字的功能就是上边那个报错，用其他发图的功能就是下边这张图的样子，但是没有报错

**Comment by MeetWq** [comment]
要写完整的字符串，像这样
```
shindanmaker_cookie="_session=xxx;"
```

**Comment by huihuiismywife** [comment]
有啦，谢谢大佬 _(:з」∠)_
