### ISSUE TITLE
'Nonetype' object has no attribute 'find' Error

### ISSUE THREAD

**Issue by Danwk2333** [noneplugin/nonebot-plugin-shindan#7]
默认占卜和其他占卜正常使用，但是有两个会报错比如https://shindanmaker.com/1031149
非推特关注的公开的链接，添加时会显示查找不到，塞到list会报错，以进行更新，cookie也正常添加

![报错3](https://user-images.githubusercontent.com/106854600/174441592-a6e97e4b-a7cc-4abd-ae69-aa54062eb803.png)
![报错2](https://user-images.githubusercontent.com/106854600/174441593-4c1cbdca-f248-41d0-9eb6-adea55efd201.png)
![报错1](https://user-images.githubusercontent.com/106854600/174441595-246a8462-e0fe-42d8-b266-cd1b4b449c46.png)
![cookie来源于相同](https://user-images.githubusercontent.com/106854600/174441820-f02df344-e3d6-4013-bc64-a4eccf61ee01.png)

**Comment by MeetWq** [comment]
这个占卜的链接好像有些区别

![Snipaste_2022-06-18_22-26-39](https://user-images.githubusercontent.com/33149974/174442859-6b5127d7-ab51-4cf8-a8a2-f211ba0457af.png)

**Comment by MeetWq** [comment]
2ec25a580a447a4e1e822ce4fd2a6c59fc8750d4 修了
