### ISSUE TITLE
Shindan lxml无法找到

### ISSUE THREAD

**Issue by FuAwake** [noneplugin/nonebot-plugin-shindan#9]
![image](https://user-images.githubusercontent.com/78325969/178631166-c6696799-0cd1-4dc7-b10d-a36b65f06ca1.png)
python版本：3.10
插件版本：最新版
lxml的问题（lxml是个啥）

**Comment by MeetWq** [comment]
pip install lxml

**Comment by FuAwake** [comment]
> pip install lxml

好吧，问题出在我更新python以后路径有问题（
